### ISSUE TITLE
这算npm install成功了么?

### ISSUE THREAD

**Issue by chapgaga** [soliury/ngFast#2]
npm info preuninstall browserify@9.0.3
npm info uninstall browserify@9.0.3
npm info postuninstall browserify@9.0.3
npm info preuninstall browser-sync@2.5.0
npm info uninstall browser-sync@2.5.0
npm info postuninstall browser-sync@2.5.0
npm info preuninstall karma@0.12.31
npm info uninstall karma@0.12.31
npm info postuninstall karma@0.12.31
npm info preuninstall gulp-sass@1.3.3
npm info uninstall gulp-sass@1.3.3
npm info postuninstall gulp-sass@1.3.3
npm ERR! not ok code 0

![](http://img.itc.cn/photo/jmFpaLDN50E)

**Comment by soliury** [comment]
很不好意思哈，现在才看到，你运行一下gulp dev看能不能执行

**Comment by soliury** [comment]
其实很多npm都是暂时没用到得，没有删除
